### ISSUE TITLE
Setting up the public key?

### ISSUE THREAD

**Issue by ryannix123** [jborean93/ansible-role-win_openssh#10]
Thank you, Jordan, for creating this project. It's fantastic! 

Quick question:

I can't get the public key setup to work. It seems like it should be working by default, but I must be missing something in the config:

My playbook:
```
  hosts: windows
  roles:
  - role: jborean93.win_openssh
  tasks:
    - name: Copy ssh public key to server(s)
      ansible.windows.win_copy:
        src: /Users/rtn361/.ssh/id_rsa.pub
        dest: C:\Users\sadmin\.ssh\authorized_key
        opt_openssh_password_auth: True
```

**Comment by jborean93** [comment]
The `opt_openssh_password_auth: True` should be a variable you define when calling the role if you want to enable password authentication like

```yaml
  hosts: windows
  roles:
  - role: jborean93.win_openssh
    opt_openssh_password_auth: True
  tasks:
    - name: Copy ssh public key to server(s)
      ansible.windows.win_copy:
        src: /Users/rtn361/.ssh/id_rsa.pub
        dest: C:\Users\sadmin\.ssh\authorized_key
```

Are you getting an error when running this, or is your private key not working when you go to connect to it later on?
